// <auto-generated />
namespace ElevenNote.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class starsshowingupstillcatchingtheerrorimhopingadbmigratewillsolvethis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(starsshowingupstillcatchingtheerrorimhopingadbmigratewillsolvethis));
        
        string IMigrationMetadata.Id
        {
            get { return "201805262123204_stars showing up still catching the error.. im hoping a dbmigrate will solve this"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
